       INTEGER FUNCTION  GLOBALINDEX_Z(LIND,GDIM,NPY,NPZ,ME)

!   LIND = INDEX OF AN ELEMENT OF SHEARED ARRAY IN THE LOCAL MEMORY
!   GDIM = GLOBAL DIMENSION OF AN ARRAY TO BE SHEARED AMONG PROCESSORS
!   NP   = NUMBER OF PROCESSOR
!   ME   = INDEX OF THE CALLING PROCESSOR (starting from ZERO)
!  
!   THIS FUNCTION RETURN THE ABSOLUTE INDEX OF THE LOCAL 
!   ARRAY ELEMENT "LIND" 

       IMPLICIT NONE

       INTEGER LIND,GDIM,NPY,NPZ,ME,R,Q
       Q = INT(GDIM/NPZ)
       GLOBALINDEX_Z = Q*(ME - INT(ME/NPZ) * NPZ) + LIND

       RETURN
       END
